### ISSUE TITLE
Extension configuration under Windows

### ISSUE THREAD

**Issue by nowinskp** [sadesyllas/vscode-workspace-switcher#11]
I'm having trouble running this extension properly on Windows 10. 

When I try to switch workspaces, I properly get the workspace list but after choosing one, I get the following error:
`Command failed: "C:/Program Files/Microsoft VS Code/Code.exe" -n "C:\Users\[my-username]\Projects\rustyrock.code-workspace" C:/Program Files/Microsoft VS Code/Code.exe: bad option: -n`

It all works OK if run manually via command line.

**Comment by dwhall** [comment]
The same holds true for Windows 7.  My interpretation of the error message is that it is trying to execute the .code-workspace file itself.
`Command failed: code -r "d:\projects\foo\bar.code-workspace" d:\projects\foo\bar.code-workspace:2 "settings": { ^ SyntaxError: Unexpected token : at createScript (vm.js:53:10) at Object.runInThisContext (vm.js:95:10) at Module._compile (module.js:543:28) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:488:32) at tryModuleLoad (module.js:447:12) at Function.Module._load (module.js:439:3) at Module.require (module.js:498:17) at Function.Module._preloadModules (module.js:665:12) at preloadModules (bootstrap_node.js:404:38)`

**Comment by graphem** [comment]
Same issue here

**Comment by sadesyllas** [comment]
Please, use `"C:\\Program Files\\Microsoft VS Code\\bin\code.cmd"`, instead of `"C:\\Program Files\\Microsoft VS Code\\Code.exe"` when setting the path to the executable in the configuration.

This script is the one that accepts the `-n` and `-r` options, thus able to start with a specific workspace file.

After doing this, does it still fail?

**Comment by dwhall** [comment]
Thank you!  That fixed the issue for me.  The path needs a tiny correction, a double-backslash before code.cmd:
`"C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd"`

**Comment by nowinskp** [comment]
@sadesyllas @dwhall Thank you, guys! I also confirm that it works now!

**Comment by EEKimS** [comment]
I have `"vscodeWorkspaceSwitcher.codeExecutable": "C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd",` in my settings file, and i am still getting this error. I did recently have to reinstall due to a terrible crash during a VS Code update, but i am at a loss for why my computer doesn't seem to be looking at the setting file at all
