### ISSUE TITLE
Add support for wildcards in vscodeWorkspaceSwitcher.paths

### ISSUE THREAD

**Issue by Keeper82** [sadesyllas/vscode-workspace-switcher#8]
It could be a nice idea to add support for wildcards so with a couple of paths, several others can be included.

For example:

```
vscodeWorkspaceSwitcher.paths = [
    '~/projects/*/'
]
```

**Comment by sadesyllas** [comment]
@Keeper82 , the main problem with this is that with `Ctrl+k Shift-W` you can now choose one of the folders in `vscodeWorkspaceSwitcher.paths` to save the workspace file.

This was implemented because I found it particularly annoying to have to navigate to the same place every time I want a new workspace saved and to reduce the steps for saving a new one.

So, I would have to find the time to fix this (in a nice way 😃 ) to allow wildcards or to discard this functionality (`Ctrl+k Shift-W`) altogether.

By the way have you found this feature useful at all (I mean `Ctrl+k Shift-W` to save a new workspace)?

And thanks for the suggestion.

**Comment by sadesyllas** [comment]
@Keeper82 please update to version v1.6.0.

The example you provided must now become (**notice the double \* in the directory glob**):

```
vscodeWorkspaceSwitcher.paths = [
    '~/projects/**/'
]
```

Better late than never I guess.

Thank you for this idea!
